EXTRA_CFLAGS += ""
CFLAGS += $(EXTRA_CFLAGS) -Wno-stringop-truncation
#LDFLAGS += -L./algorithm
LDLIBS += -lpthread -lmediaAPI -ltuning -lispaml -lm

SRCS = \
	mediactrlsrc.c

TARGET = mediactrlsrc

include ../makefile.inc
