TARGET = hdmictrl
SRCS = hdmictrl.c
EXTRA_CFLAGS += ""
CFLAGS = -I../include
CFLAGS += $(EXTRA_CFLAGS) -Wno-stringop-truncation
LDFLAGS += -L../
LDLIBS += -lm -lrt -lpthread -ltvclient


include ../makefile.inc
